name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

        steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Dependencies
      run: cd front-end && npm install

    - name: Build
      run: cd front-end && npm run build

    - name: Deploy to Firebase
      run: |
        cd front-end
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
